//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string PostContent { get; set; }
        public string Url { get; set; }
        public string Meta { get; set; }
        public string Type { get; set; }
        public string ShortDescription { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> DatePosted { get; set; }
        public string img { get; set; }
    }
}
